[common]
platform = espressif32@6.9.0
framework = arduino
lib_deps = zerokol/eFLL@^1.4.1
monitor_speed = 115200
extra_scripts = post:script_build_branch.py

[env:esp32doit-devkit-v1]
platform = ${common.platform}
board = esp32doit-devkit-v1
framework = ${common.framework}
lib_deps = ${common.lib_deps}
monitor_speed = ${common.monitor_speed}
build_flags = -DMC_BOARD_DOIT
extra_scripts = ${common.extra_scripts}

[env:esp32-s3-devkitc-1]
platform = ${common.platform}
board = esp32-s3-devkitc-1
framework = ${common.framework}
lib_deps = ${common.lib_deps}
monitor_speed = ${common.monitor_speed}
build_flags = -DMC_BOARD_S3
extra_scripts = ${common.extra_scripts}